name: Monitor de Noticias con IA

on:
  schedule:
    - cron: '0 8,16 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ejecutar-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerías
        run: |
          pip install google-genai pydantic

      - name: Ejecutar script de análisis
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Auto commit de la página web
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización diaria de portal de noticias"
          file_pattern: 'index.html'
